apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tripweaver.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tripweaver-api
  template:
    metadata:
      labels:
        app: tripweaver-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: INDEX_PATH
              value: /data/index.json
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
