apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripweaver-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripweaver-api
  template:
    metadata:
      labels:
        app: tripweaver-api
    spec:
      # Security hardening for CVE-2025-8941 mitigation
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: tripweaver-api:local
          ports:
            - containerPort: 8000
          env:
            - name: INDEX_PATH
              value: /data/index.json
          volumeMounts:
            - name: data
              mountPath: /data
          # Container-level security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: data
          emptyDir: {}
